#==========================spring设置===========================================
spring:
  main:
    lazy-initialization: false  #懒加载
  profiles:
    active:
      - swagger  #swagger配置
      - dev #数据源配置
  task:
    scheduling:
      pool:
        size: 10 #定时任务线程池大小设置默认1设置为5
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss #jackson时间格式化类
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss #日期格式化
  servlet:
    multipart:
      max-request-size: 30MB
      file-size-threshold: 0 #文件写入磁盘的阈值,设置为0，即上传就存储在服务器,如果是100则表示小于100会存储在内存
      max-file-size: 30MB    #单个文件上传的最大值
server:
  port: 8080
#==========================mybatis配置=======================================
mybatis-plus:
  global-config:
    db-config:
      id-type: assign_id #全局主键使用雪花算法生成id
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl   #打印sql
  mapper-locations: "classpath:mapper/*.xml"
#==========================分页设置===========================================
pagehelper:
  helper-dialect: mysql  #分页方言设置
  properties: propertyValue
  reasonable: true  # 是否启用合理化分页（根据页码自动计算合理的值）
  defaultCount: true # 分页插件默认参数支持 default-count 形式，自定义扩展的参数，必须大小写一致
  params: count=countSql  # 分页参数映射，count指定总数，可以自定义
  support-methods-arguments: true   #支持自定义参数
